[common]
listen = ":9090"
max-cpu = 1
keep-duplicates = true

[clickhouse]
url = "http://localhost:8123"
data-table = "graphite"
tree-table = "graphite_tree"
reverse-tree-table = ""
tag-table = ""
rollup-conf = "/etc/graphite-clickhouse/rollup.xml"
extra-prefix = ""
data-timeout = "1m0s"
tree-timeout = "1m0s"

[logging]
file = "stdout"
level = "info"
encoding = "mixed"
encoding-time = "iso8601"
encoding-duration = "seconds"
